/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "ATK": "攻击",
    "Auto-saving": "自动保存",
    "Current Zone": "当前区域",
    "DEF": "防御",
    "Daily": "日常",
    "EQUIP BEST": "装备最佳",
    "Kills": "击杀",
    "• Drops:": "• 掉落:",
    "Equipment": "装备",
    "Head": "头部",
    "Hands": "手部",
    "Feet": "脚部",
    "Initializing...": "初始化...",
    "Inventory": "库存",
    "Inventory (": "库存 (",
    "Legs": "腿部",
    "Lv.": "等级",
    "Neck": "脖子",
    "Prestige": "声望",
    "Reset": "重置",
    "Rest": "休息",
    "Silver": "银币",
    "Shield": "护盾",
    "Skills": "技能",
    "Speed:": "速度:",
    "Spider Den": "蜘蛛巢穴",
    "Stats": "属性",
    "XP": "经验值",
    "Belt": "腰带",
    "Continue Playing": "继续游戏",
    "Map": "地图",
    "LOADING GAME ASSETS...": "正在加载游戏资源...",
    "Map": "地图",
    "Silver Earned": "获得的银币",
    "Welcome Back!": "欢迎回来!",
    "You were away for": "你离开了",
    "Offline Progress": "离线进度",
    "Press Enter or click anywhere to close": "按回车键或点击任意位置以关闭",
    "Enhance": "强化",
    "Chest": "宝箱",
    "Enemies Defeated": "敌人被击败了",
    "LEVEL UP!": "升级了!",
    "PRESETS": "预设",
    "Click to equip · Right-click to salvage": "点击可装备 · 右键点击可回收",
    "Combat": "战斗",
    "Agility": "敏捷",
    "Attributes": "属性",
    "Armor": "护甲",
    "Crit %": "暴击率 %",
    "Crit DMG": "暴击伤害",
    "Damage": "伤害",
    "Dodge": "闪避",
    "Dmg Reduction": "伤害减少",
    "HP Regen": "生命值回复",
    "Experience Gained": "获得经验值",
    "Fight": "战斗",
    "Base Stats": "基础属性",
    "Common": "普通",
    "DMG": "伤害",
    "Item Power": "物品战力",
    "Rating": "评分",
    "Scales with": "提升",
    "STR": "力量",
    "sword": "剑",
    "weapon": "武器",
    "Empty Slot": "空栏位",
    "Equipment Presets": "套装预设",
    "Save Current": "保存当前",
    "Save and load equipment configurations": "保存和加载装备配置",
    "Presets save your currently equipped gear. Loading will swap with inventory.": "预设保存你当前装备的装备。加载操作会替换当前的装备栏内容。",
    "^ UPGRADE ^": "^ 升级 ^",
    "+HP": "+生命值",
    "+DMG": "+伤害",
    "Crit": "暴击",
    "Epi": "史诗",
    "Div": "神圣",
    "Filter:": "过滤器:",
    "Speed": "速度",
    "Unc": "罕见",
    "Uncommon": "罕见",
    "vs Equipped:": "vs 已装备:",
    "Special Effects": "特殊效果",
    "Lifesteal": "吸血",
    "Keep effects:": "保留效果:",
    "Com": "普通",
    "Myt": "神话",
    "Rar": "稀有",
    "HP": "生命值",
    "PWR": "力量",
    "Sandals": "凉鞋",
    "Slot Empty - Equipping will add stats!": "空槽 - 装备会增加属性！",
    "Gold%": "金币%",
    "INT": "智力",
    "v DOWNGRADE v": "v 降级 v",
    "AGI": "敏捷",
    "Adjust audio and game settings": "调整声音和游戏设置",
    "Audio Settings": "音频",
    "By Power": "按战力",
    "By Rarity": "按稀有度",
    "By Slot": "按槽位",
    "Credits": "鸣谢",
    "Display Settings": "显示设置",
    "Engine": "引擎",
    "Game": "游戏",
    "for keyboard shortcuts": "快捷键",
    "Gear Grinder": "装备研磨者",
    "How to organize inventory items": "如何整理库存物品",
    "Inventory Sort": "库存排序",
    "Increase text size for better readability": "增大文字大小以提高可读性",
    "Large": "大",
    "Music": "音乐",
    "Master Volume": "主音量",
    "MUTED": "静音",
    "Normal": "正常",
    "Press": "按",
    "React + PixiJS": "React + PixiJS",
    "Sound Effects": "音效",
    "Stop Music": "停止音乐",
    "Test Music": "测试音乐",
    "Test SFX": "测试音效",
    "Text Size": "文本大小",
    "VXRGE": "VXRGE",
    "X-Large": "加大",
    "SALVAGE (": "回收 (",
    "Prestige Stones": "声望石",
    "Prestige System": "声望系统",
    "Prestige Level": "声望等级",
    "Permanent Upgrades": "永久升级",
    "Stones)": "石)",
    "Thorns": "荆棘",
    "Upgrade (": "升级 (",
    "XP Mastery": "经验精通",
    "Starting Bonus": "初始奖励",
    "Reset progress for permanent power": "重置进度获得永久战力",
    "Stiletto": "小剑",
    "Perform Ascension": "进行转生",
    "Locked": "未解锁",
    "Empty": "空",
    "Claim Reward!": "领取奖励!",
    "Daily Rewards": "每日奖励",
    "Day": "天数",
    "Welcome back!": "欢迎回来!",
    "Start your streak today!": "从今天开始，开启你的连续签到吧！",
    "Already Claimed Today": "今日已领取",
    "Current streak:": "当前连签:",
    "days": "天",
    "Keep it up!": "保持住!",
    "Next reward in:": "距离下一个奖励还有:",
    "Confirm?": "确认?",
    "HP:": "生命值:",
    "GO": "前往",
    "DMG:": "伤害:",
    "HERE": "这里",
    "Set": "套装",
    "Zone": "区域",
    "Abyssal Eye": "深渊之眼",
    "Arachnid Lair": "蜘蛛巢穴",
    "Bat Hollow": "蝙蝠洞穴",
    "Bear's Domain": "熊的领地",
    "Beetle Burrow": "甲虫洞穴",
    "Behemoth": "巨兽",
    "Blooming Marsh": "繁花沼泽",
    "Cerberus": "塞伯鲁斯",
    "Crow Demon": "乌鸦恶魔",
    "Crow's Nest": "乌鸦巢穴",
    "Crystal Caves": "水晶洞穴",
    "Cursed Fields": "诅咒之地",
    "Dark Hollow": "黑暗洞穴",
    "Dark Wolf King": "黑暗狼王",
    "Demon Lord": "恶魔之王",
    "Dwarven Mines": "矮人矿井",
    "Eye of the Abyss": "深渊之眼",
    "Frozen Wastes": "冰封荒原",
    "Fungal Grove": "真菌林",
    "Gelatinous Depths": "胶状深渊",
    "Golem Quarry": "魔像采石场",
    "Hellhound Lair": "地狱犬巢穴",
    "Horned Behemoth": "角形巨兽",
    "Hornet's Nest": "黄蜂巢穴",
    "Imp Hollow": "幽灵洞穴",
    "Mantis Hive": "螳螂之巢",
    "Murky Swamp": "浑浊沼泽",
    "Ooze Caverns": "黏液洞穴",
    "Owl's Perch": "猫头鹰栖息地",
    "Poison Garden": "毒药花园",
    "Primal Woods": "原始森林",
    "Pumpkin Patch": "南瓜地",
    "Shadow Webs": "阴影网",
    "Shadow Wolf": "阴影狼",
    "Shadow Wolf Alpha": "阴影狼之王",
    "Skull Garden": "骷髅花园",
    "Slime Pits": "史莱姆坑",
    "Slime Pools": "史莱姆池",
    "Slime Wastes": "史莱姆废墟",
    "Spider Matriarch": "蜘蛛女王",
    "Vampire Den": "吸血鬼巢穴",
    "Wolf Territory": "狼的领地",
    "World Map": "世界地图",
    "Damage Breakdown": "伤害细分",
    "Intelligence": "智力",
    "MAX": "最大",
    "Luck": "幸运",
    "Points:": "点数:",
    "RESPEC": "洗点",
    "SAVE": "保存",
    "Strength": "力量",
    "Silver %": "银币 %",
    "XP %": "经验值 %",
    "VIT": "活力",
    "Vitality": "活力",
    "/hit": "/攻击",
    "Armor Reduction": "护甲降低",
    "Base Hit": "基础攻击",
    "Avg Damage/Hit": "平均伤害/攻击",
    "Critical Hit (": "暴击 (",
    "Damage Output": "伤害输出",
    "Enemy Base Dmg": "敌人基础伤害",
    "Enemy HP": "敌人生命值",
    "Est. Kill Time": "预计击杀时间",
    "You Take": "你受到",
    "True DPS": "真实每秒造成伤害",
    "AUTO +": "自动 +",
    "Next": "下一级",
    "Current": "当前",
    "Awakening Progress": "觉醒进度",
    "HP +": "生命值 +",
    "DMG +": "伤害 +",
    "ENHANCE": "强化",
    "Success Rate": "成功率",
    "Select Item": "选择物品",
    "Select an item": "选择一件物品",
    "Next awakening at +": "下一次觉醒在 +",
    "to go)": "还差)",
    "Load": "加载",
    "Update": "更新",
    "Req Lv.": "要求 等级",
    "Mastery": "精通",
    "Critical Eye": "暴击之眼",
    "Combat Skills": "战斗技能",
    "ACTIVE": "主动",
    "Berserker": "狂战士",
    "Fortitude": "坚韧",
    "Gold Rush": "淘金热",
    "Lucky Find": "幸运发现",
    "Power Strike": "强力打击",
    "Regeneration": "再生",
    "Skin": "皮肤",
    "Swift Blade": "迅捷之刃",
    "Thorny Skin": "荆棘皮肤",
    "Toughness": "韧性",
    "Transcendence": "超越",
    "Vampiric": "吸血鬼",
    "EQUIP": "装备",
    "More": "更多",
    "XP%": "经验值%",
    "System Unlocks": "系统解锁",
    "SALVAGE": "回收",
    "↑ UPGRADE": "↑ 升级",
    "↓ DOWNGRADE": "↓ 降级",
    "Astral Realm": "星际领域",
    "Cosmic Realm": "宇宙领域",
    "and increases Prestige Level.": "并且提升声望等级。",
    "Eternal Bulwark": "永恒堡垒",
    "Eternal Fortune": "永恒财富",
    "Eternal Fury": "永恒之怒",
    "Eternal Guard": "永恒守卫",
    "Eternal Haste": "永恒速度",
    "Eternal Leech": "永恒吸血",
    "Eternal Precision": "永恒精准",
    "Eternal Regen": "永恒再生",
    "Eternal Strength": "永恒力量",
    "Eternal Vitality": "永恒活力",
    "Formula: 10 + Level/2. Extra stones drop from Prestige zones (40+).": "公式：10 +等级/2。声望区域（40+）掉落额外石头",
    "Primordial Realm": "原初领域",
    "Requirement: Defeat the Dark Wolf King in Zone 39. Resets all progress but rewards": "要求：在区域 39 击败暗狼王。会重置所有进度，但会给予奖励",
    "Tap to equip · Long-press to salvage": "点击装备 · 持住长按以回收",
    "% bonus)": "% 加成)",
    "Awakened": "已觉醒",
    "FAIL": "失败",
    "fails (+": "失败 (+",
    "Pity:": "可惜:",
    "STOP (+": "停止 (+",
    "Awakening Bonuses": "觉醒加成",
    "DONE": "完成",
    "Boss Slayer": "Boss杀手",
    "Crafting": "制作",
    "Blacksmith": "铁匠",
    "Defeat all bosses": "击败所有Boss",
    "Slayer": "杀手",
    "Rich": "富有",
    "Unlocked": "已解锁",
    "Upgrader": "升级者",
    "Achievement Unlocked!": "成就已解锁!",
    "Adventurer": "冒险者",
    "Defeat your first boss": "击败你的第一个Boss",
    "Explorer": "探索者",
    "First Blood": "第一滴血",
    "Apprentice": "学徒",
    "Artisan": "工匠",
    "Champion": "冠军",
    "Conqueror": "征服者",
    "Expert": "专家",
    "Exploration": "探索",
    "Journeyman": "熟练工",
    "Legend": "传奇",
    "Master": "大师",
    "Master Smith": "铁匠大师",
    "Millionaire": "百万富翁",
    "Pocket Change": "零花钱",
    "Prestige for the first time": "第一次获得声望",
    "Progress": "进展",
    "Reach prestige level 5": "达到声望等级5",
    "Reborn": "重生",
    "Transcendent": "超凡脱俗",
    "Veteran": "老兵",
    "Warrior": "战士",
    "Wealth": "财富",
    "Wealthy": "富有",
    "Boss Stones": "Boss石",
    "Close this menu": "关闭这个菜单",
    "Keyboard Shortcuts": "键盘快捷键",
    "Navigate between tabs": "在标签页之间切换",
    "or": "或",
    "S+": "S+",
    "to close": "以关闭",
    "Toggle this help menu": "切换此帮助菜单",
    "Switch tabs (Inventory, Stats, Enhance, Skills, Map, Prestige, Achievements, Settings)": "切换标签页（库存、属性、强化、技能、地图、声望、成就、设置）",
    "Epic": "史诗",
    "Rare": "稀有",
    "Paws": "爪子",
    "Gauntlets": "护腕",
    "Legguards": "护腿",
    "Chainmail": "链甲",
    "Crimson Edge": "深红之刃",
    "Grasp": "把握",
    "Talon": "魔爪",
    "Crow Flight: +20% HP, +8% Dodge": "乌鸦飞行：+20%生命，+8%躲避",
    "Crystal Staff": "水晶法杖",
    "Hellhound Fury: +5% Lifesteal, +30% Crit DMG": "地狱猎犬之怒：+5%生命偷取，+30%暴击伤害",
    "Knight Helm": "骑士头盔",
    "Shadow Fang": "暗影獠牙",
    "Silver Locket": "银质吊坠",
    "Skull Crusher": "颅骨破碎机",
    "Studded Belt": "钉甲腰带",
    "Viper Strike": "毒蛇突击",
    "Demon Fury: +30% DMG, +15% Speed": "恶魔之怒：+30%伤害，+15%速度",
    "Legendary": "传说",
    "Arcane Focus": "奥术聚焦",
    "Assassin Blade": "刺客之刃",
    "Dragonskin Treads": "龙皮战靴",
    "Dragonslayer": "屠龙者",
    "Drake Claws": "德雷克爪子",
    "Titan Maul": "泰坦之锤",
    "Void Scepter": "虚空权杖",
    "Spider Sense: +12% All Stats": "蜘蛛感知：所有属性提升 12%",
    "Phoenix Crown": "凤凰王冠",
    "Soul Gem": "灵魂宝石",
    "Mythic": "神话",
    "Bulwark": "壁垒",
    "Void Legguards": "虚空护腿",
    "Void Sash": "虚空腰带",
    "Abyssal Plate": "深渊板甲",
    "Void Grip": "虚空之握",
    "Soul Reaver": "灵魂掠夺者",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "SP": "SP",
    "Web": "网",
    "Treads": "战靴",
    "Spinnerets": "喷丝器",
    "Carapace": "外壳",
    "Eye": "眼",
    "Silk": "丝",
    "Visor": "面甲",
    "Scale": "鳞",
    "Hooves": "兽蹄",
    "Plate": "板",
    "Aegis": "羊皮盾",
    "Plated Boots": "板靴",
    "Ward": "看守",
    "Wings": "翅膀",
    "Girdle": "束带",
    "Feather": "羽毛",
    "Crown": "王冠",
    "Chain": "链甲",
    "Claws": "爪",
    "Fang": "牙",
    "Greaves": "护胫",
    "Guard": "守卫",
    "Heart": "心",
    "Hide": "皮",
    "Skull": "骷髅",
    "Coif": "发髻",
    "Tower Shield": "塔盾",
    "Saber": "军刀",
    "Kite": "风筝盾",
    "War Hammer": "战锤",
    "pc": "pc",
    "Plate Greaves": "板胫",
    "Plate Fists": "板拳",
    "Plate Armor": "板甲",
    "Esc": "Esc",
    "Boss": "Boss",
    "Enh": "Enh",
    "Inv": "Inv",
    "vs": "vs",
    "katana": "武士刀",
    "Katana": "武士刀",
    "Scythe": "镰刀",
    "scythe": "镰刀",
    "greataxe": "巨斧",
    "Greataxe": "巨斧",
    "Wraps": "披肩",
    "Tunic": "长袍",
    "Pants": "裤子",
    "Wand": "魔杖",
    "Hood": "兜帽",
    "Blade": "刀刃",
    "Mace": "权杖",
    "Dagger": "匕首",
    "Buckler": "圆盾",
    "Pendant": "吊坠",
    "Necklace": "项链",
    "Vest": "背心",
    "Shiv": "短剑",
    "Club": "棍",
    "DR%": "伤害减少%",
    "Cap": "帽子",
    "Boots": "靴子",
    "belt": "腰带",
    "Amulet": "护符",
    "amulet": "护符",
    "Leggings": "护腿",
    "Staff": "法杖",
    "dagger": "匕首",
    "mace": "权杖",
    "helmet": "头盔",
    "gloves": "手套",
    "Gloves": "手套",
    "ARM": "胳膊",
    "armor": "盔甲",
    "boots": "靴子",
    "Leg": "传说",
    "legs": "腿部",
    "shield": "盾牌",
    "staff": "法杖",
    "Sword": "生锈的剑",
    "C.Shard": "C.碎片",
    "E.Stone": "强化石",
    "B.Orb": "B.宝珠",
    "% DMG per point)": "% 伤害每点)",
    "% Crit": "% 暴击",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "⚔": "⚔",
    "?": "?",
    "!": "!",
    "(+": "(+",
    "!": "!",
    "%": "%",
    "▼": "▼",
    "★": "★",
    "🎵": "🎵",
    "🔊": "🔊",
    "🔒": "🔒",
    "🔔": "🔔",
    "🌙": "🌙",
    "@": "@",
    "^": "^",
    "&": "&",
    "--": "--",
    "×": "×",
    "✓": "✓",
    "→": "→",
    "✦": "✦",
    "·": "·",
    "◆": "◆",
    "←": "←",
    "🔥": "🔥",
    "⭐": "⭐",
    "": "",
    "": "",
    "=": "=",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Gear Grinder v": "装备研磨机 v",
    "Wooden ": "木制的",
    "Rusty ": "生锈的",
    "Leather ": "皮",
    "Cloth ": "布",
    "Bead ": "珠链",
    "Bronze ": "青铜",
    "Confirm?": "铁",
    "Oak ": "橡木",
    "Rope ": "绳索",
    "Flanged ": "法兰式",
    "Iron ": "铁",
    "Mystic ": "神话",
    "Steel ": "钢",
    "Crow Demon ": "乌鸦恶魔",
    "Cerberus ": "地狱犬",
    "Chain ": "链条",
    "Reduce damage taken by ": "减少受到的伤害 ",
    "Demon Lord ": "恶魔领主",
    "Dragon ": "龙",
    "Matriarch ": "女族长",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "%/s": "%/秒",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\/([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\+([\d\.,]+)!$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) \($/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Heal for (.+) of damage dealt$/, '治疗造成伤害的 $1'],
    [/^Reflect (.+) damage back to attackers$/, '将 $1 的伤害反弹给攻击者'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Loading (.+)...$/, '正在加载 $1...'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^\+([\d\.]+) Stat Points$/, '+$1 属性点'],
    [/^\+([\d\.]+) Pts$/, '+$1 点数'],
    [/^\+([\d\.]+)s$/, '+$1 秒'],
    [/^\+([\d\.]+) B.Orb$/, '+$1 B.宝珠'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% crit, \+([\d\.]+)\% dodge, \+([\d\.]+)\% speed, \+([\d\.]+)\% dagger\/katana DMG$/, '+$1% 暴击, +$2% 闪避, +$3% 速度, +$4% 匕首/武士刀 伤害'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) armor, \+([\d\.]+)\% regen\/s, \+([\d\.]+)\% DR, \+([\d\.]+)\% mace DMG$/, '+$1 生命值, +$2 护甲, +$3% 回复/秒, +$4% 伤害减少, +$5% 权杖 伤害'],
    [/^\+([\d\.]+)\% XP, \+([\d\.]+)\% staff DMG per point$/, '每点 +$1% 经验值, +$2% 法杖伤害'],
    [/^\+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% HP$/, '+$1% 暴击率, +$2% 生命值'],
    [/^\+([\d\.]+)\% Crit DMG, \+([\d\.]+)\% DMG$/, '+$1% 暴击伤害, +$2% 伤害'],
    [/^\+([\d\.]+)\% Crit, \+([\d\.]+)\% Crit DMG$/, '+$1% 暴击, +$2% 暴击伤害'],
    [/^\+([\d\.]+)\% Crit DMG, \+([\d\.]+)\% Thorns$/, '+$1% 暴击伤害, +$2% 荆棘'],
    [/^\+([\d\.]+)\% HP, \+([\d\.]+)\% Crit Chance$/, '+$1% 生命值, +$2% 暴击率'],
    [/^\+([\d\.]+)\% DMG, \+([\d\.]+)\% Thorns$/, '+$1% 伤害, +$2% 荆棘'],
    [/^\+([\d\.]+)\% DMG, \+([\d\.]+)\% HP$/, '+$1% 伤害, +$2% 生命值'],
    [/^\+([\d\.]+)\% gold, \+([\d\.]+)\% crit DMG per point$/, '每点 +$1% 金币, +$2% 暴击伤害'],
    [/^\+([\d\.]+) flat DMG, \+([\d\.]+)\% sword\/scythe\/greataxe DMG per point$/, '每点 +$1 平砍伤害, +$2% 剑/镰刀/巨斧 伤害'],
    [/^([\d\.]+)\% thorns damage$/, '$1% 荆棘伤害'],
    [/^([\d\.]+)\% chance to avoid attacks$/, '$1% 几率躲避攻击'],
    [/^\+([\d\.]+)\% chance to deal critical hits$/, '+$1% 几率造成暴击'],
    [/^\+([\d\.]+)\% flat damage bonus$/, '+$1% 平砍伤害加成'],
    [/^\+([\d\.]+)\% critical hit damage$/, '+$1% 暴击伤害'],
    [/^\+([\d\.]+)\% gold from enemies$/, '+$1% 来自敌人的金币'],
    [/^\+([\d\.]+)\% attack speed$/, '+$1% 攻击速度'],
    [/^\+([\d\.]+)\% base lifesteal$/, '+$1% 基础吸血'],
    [/^\+([\d\.]+)\% gold find per level$/, '+$1% 金币发现每级'],
    [/^\+([\d\.]+)\% attack speed per level$/, '+$1% 攻击速度每级'],
    [/^\+([\d\.]+)\% crit chance per level$/, '+$1% 暴击几率每级'],
    [/^\+([\d\.]+)\% crit damage per level$/, '+$1% 暴击伤害每级'],
    [/^\+([\d\.]+)\% base DMG per level$/, '+$1% 基础伤害每级'],
    [/^\+([\d\.]+) base armor per level$/, '+$1 基础护甲每级'],
    [/^\+([\d\.]+) gold, \+([\d\.]+) ore\/leather on prestige per level$/, '每级 +$1 金币, +$2 矿石/皮革 在声望时'],
    [/^\+([\d\.]+)\% HP regen\/sec per level$/, '每级 +$1% 生命值回复/秒'],
    [/^\+([\d\.]+)\% lifesteal per level$/, '+$1% 吸血每级'],
    [/^\+([\d\.]+)\% base HP per level$/, '+$1% 基础生命值每级'],
    [/^\+([\d\.]+)\% XP gain per level$/, '+$1% 经验增益每级'],
    [/^\+([\d\.]+)\% base armor per level$/, '+$1% 基础护甲每级'],
    [/^\+([\d\.]+)\% damage reduction per level$/, '+$1% 伤害降低每级'],
    [/^\+([\d\.]+)\% crit chance$/, '+$1% 暴击几率'],
    [/^\+([\d\.]+)\% All Stats$/, '+$1% 所有属性'],
    [/^\+([\d\.]+)\% all stats$/, '+$1% 所有属性'],
    [/^\+([\d\.]+)\% material drop$/, '+$1% 材料掉落'],
    [/^\+([\d\.]+)\% damage reduction$/, '+$1% 伤害减少'],
    [/^\+([\d\.]+)\% HP regen\/sec$/, '+$1% 生命值回复/秒'],
    [/^\+([\d\.]+)\% experience gained$/, '+$1% 经验增益'],
    [/^\+([\d\.]+)\% Lifesteal$/, '+$1% 吸血'],
    [/^\+([\d\.]+)\% DMG$/, '+$1% 伤害'],
    [/^\+([\d\.]+)\% Dodge$/, '+$1% 闪避'],
    [/^\+([\d\.]+)\% gold$/, '+$1% 金币'],
    [/^\+([\d\.]+)\% damage$/, '+$1% 伤害'],
    [/^\+([\d\.]+)\% HP$/, '+$1% 生命值'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^Restore ([\d\.]+)\% max HP per second$/, '每秒回复 $1% 生命值上限'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) maximum HP$/, '+$1 生命值上限'],
    [/^\+([\d\.,]+) flat damage bonus$/, '+$1 平砍伤害加成'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.,]+)s$/, '+$1s'],
    [/^\+([\d\.]+) E.St$/, '+$1 E.St'],
    [/^\+([\d\.]+) P.St$/, '+$1 P.St'],
    [/^\+([\d\.]+) C.Sh$/, '+$1 C.Sh'],
    [/^([\d\.,]+) items$/, '$1 物品'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+) minute$/, '$1 分钟'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Prestige ([\d\.,]+)$/, '声望 $1'],
    [/^Earn ([\d\.,]+) total silver$/, '总计赚取 $1 银币'],
    [/^Defeat ([\d\.,]+) enemies$/, '击败 $1 敌人'],
    [/^Day ([\d\.,]+) Reward$/, '天数 $1 奖励'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Enhance any item to \+([\d\.,]+)$/, '强化任意物品到 +$1'],
    [/^Unlock zone ([\d\.,]+)$/, '解锁区域 $1'],
    [/^Reach level ([\d\.,]+)$/, '达到等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);